### ISSUE TITLE
Message problems

### ISSUE THREAD

**Issue by alchaussee** [Dr-Neferious/CS3251-Hw3#7]
It looks like messages arent properly setting values. Like why are all of the flags set in the message or why is the window size 32767

![screenshot from 2015-04-14 18 27 58](https://cloud.githubusercontent.com/assets/3220591/7148768/3193d982-e2d4-11e4-849c-bd32105c4e74.png)

**Comment by barulicm** [comment]
This is probably because were not explicitly calling the constructor when making new messages.

**Comment by alchaussee** [comment]
i fixed it by initializing all variables of message in its constructor

**Comment by barulicm** [comment]
👍

**Comment by alchaussee** [comment]
this also seems to fix the problem where the server and client dont connect and get stuck at the syn message
